CREATE TABLE `lender`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `middlename` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `type` INT(3) NOT NULL,
  `dob` DATETIME NULL,
  `gender` INT(3) NULL,
  `marital_status` INT(3) NULL,
  `work_status` INT(3) NULL,
  `residential_status` INT(3) NULL,
  `currency` INT(3) NULL,
  `image_url` VARCHAR(45) NULL,
  `referral_code` VARCHAR(45) NULL,
  `role` INT(3) NULL,
  `father` VARCHAR(45) NULL,
  `gcm_id` VARCHAR(45) NULL,
  `status` INT(3) NOT NULL,
  `create_user` INT NULL DEFAULT -1,
  `create_ts` DATETIME NOT NULL,
  `update_user` INT NULL DEFAULT -1,
  `update_ts` DATETIME NOT NULL,
  PRIMARY KEY (`id`));